### ISSUE TITLE
android，未继承扫码，如何开启debug

### ISSUE THREAD

**Issue by fanlvwen** [weexteam/weex-debugger#10]
老版weex-devtool:
android原生代码配置如下：
WXEnvironment.sDebugServerConnectable = true;
WXEnvironment.sRemoteDebugMode = true;
WXEnvironment.sRemoteDebugProxyUrl = "ws://" + host + ":8088/debugProxy/native";

weex启动debug：weex debug src -e index.vue

都是配置好的，启动app后chrome能看到设备列表，然后可以debug，老版的devtool一直在用，
后来升级到最新版debugger，就只能扫二维码，原先的weex debug src -e index.vue命令也不识别了

请问新版不扫码如何开启debug

**Comment by erha19** [comment]
see https://github.com/weexteam/weex-devtool/issues/107#issuecomment-369536396
