### ISSUE TITLE
weex debug src 打包出来的js太大

### ISSUE THREAD

**Issue by fanlvwen** [weexteam/weex-debugger#12]
Time: 52304ms
                                            Asset     Size  Chunks                    Chunk Names
           component\FillOrder\FillOrderHeader.js   473 kB      50  [emitted]  [big]  component\FillOrder\FillOrderHeader
                                ui\OrderDetail.js  3.06 MB       0  [emitted]  [big]  ui\OrderDetail
                                  ui\FillOrder.js  2.75 MB       2  [emitted]  [big]  ui\FillOrder
                                 ui\TicketList.js  2.45 MB       3  [emitted]  [big]  ui\TicketList
                             ui\TrainNumDetail.js  2.48 MB       4  [emitted]  [big]  ui\TrainNumDetail
                               ui\ResignSubmit.js  2.76 MB       5  [emitted]  [big]  ui\ResignSubmit

如果是用webpack打包，只有几百K，这就造成debug的时候，做一点修改，热更新要重新编译，要将近一分钟，请问是什么原因

**Comment by erha19** [comment]
@fanlvwen maybe it causes by the source map data, you can compile only one file while your project is too heavy.
