### ISSUE TITLE
【问题】Weex debugger 只能用于 .vue 文件吗？

### ISSUE THREAD

**Issue by biaomingzhong** [weexteam/weex-debugger#21]
需要调试一些入口使用了 vue-router 的页面怎么办？

例如:

index.js 内容为：

```
/* global Vue */

/* weex initialized here, please do not move this line */
const router = require('./router')
const App = require('@/page/Home.vue')
/* eslint-disable no-new */
new Vue(Vue.util.extend({el: '#root', router}, App))
router.push('/')
```

router.js 内容为：

```
/* global Vue */
import Router from 'vue-router'
import HelloWorld from '@/component/HelloWorld'

Vue.use(Router)

module.exports = new Router({
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld
    }
  ]
})
```

**Comment by biaomingzhong** [comment]
官方的 demo 也是，如果想要调试 `Example.vue` 也无法调试，直接报错，因为实际入口是 `Example.js` 而不是 .vue 文件

https://github.com/Hanks10100/weex-vue-examples/blob/master/src/pages/examples/Examples.vue

**Comment by erha19** [comment]
@biaomingzhong you don't need using `weex-debugger` to compile all the source, the compile support on `weex-debugger` is so poor to transform all the language like `js` or `rax`, if you have an `Example.js` can be rendered on playground, you just need to connect to weex-debugger, then scan the QR-code of this bundle.

**Comment by biaomingzhong** [comment]
Awesome
