### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by shangxinbo** [weexteam/weex-debugger#28]
windows 10 
node 8.9
npm 5.6

E:\weex>weex debug
This command need to install weex-debugger. Installing...
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\10008147\.xtoolkit\node_modules\buffertools
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\10008147\AppData\Roaming\npm-cache\_logs\2018-07-20T08_02_16_793Z-debug.log
16:02:16 : Error: fatal error!

**Comment by erha19** [comment]
@shangxinbo It dependence on `node-gyp`, you can see the document here https://github.com/nodejs/node-gyp#on-windows.
