### ISSUE TITLE
开启JS Debug报错

### ISSUE THREAD

**Issue by mario-huang** [weexteam/weex-debugger#29]
iOS 11
weexSDK 0.18.3
weex-devtool-iOS 0.16.3
weex-debugger 1.1.13

如果没开JS Debug，按钮点击正常。
如果开了JS Debug，所有点击失效，并且报错：
call [__WEEX_CALL_JAVASCRIPT__] error: jsframework has no such api

(anonymous) | @ | [Runtime]-App.js:283
-- | -- | --
  | (anonymous) | @ | [Runtime]-App.js:46
  | _emit | @ | [Runtime]-App.js:45
  | emit | @ | [Runtime]-App.js:57
  | self.onmessage | @ | [Runtime]-App.js:269

**Comment by erha19** [comment]
@myeveryheart you can upgrade your `weex-debugger` to the latest version by `weex update weex-debugger` command, and then include the latest source code of `weex sdk` from apache repo https://github.com/weexteam/weex-debugger/issues.

**Comment by fsxiaoke** [comment]
请问这个问题解决了吗？
我都升级到最新也不行啊

**Comment by mario-huang** [comment]
@fsxiaoke https://aygtech.github.io/weexbox/guide/#weexbox-debugger
