### ISSUE TITLE
A network segment Scan QR code network error 

### ISSUE THREAD

**Issue by 501956430** [weexteam/weex-debugger#3]
The latest Weex-devtool:

![qq 20180124152235](https://user-images.githubusercontent.com/20204491/35319356-7348f184-011a-11e8-9052-0ed838a885a4.jpg)

**Comment by erha19** [comment]
@501956430 Please provide your platform infomation？ like the android version and which type of the phone？

**Comment by erha19** [comment]
@501956430 solved https://github.com/weexteam/weex-toolkit/issues/265.
