### ISSUE TITLE
界面一直在loading

### ISSUE THREAD

**Issue by liuruizhe** [weexteam/weex-debugger#30]
界面一直在loading，无法加载出。mac终端提示Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
You may not have installed chromium properly, you can find solution here https://github.com/weexteam/weex-toolkit/issues/275.

**Comment by liuruizhe** [comment]
求大神帮忙看下， 为什么一直提示Chromium。升级npm，node版本，切换各种镜像库都尝试过。

**Comment by erha19** [comment]
@liuruizhe728 it causes by the wrong installation, you need to remove the cache file from `~/.xtoolkit/node_modules/weex-debugger`, you can use the command `weex remove weex-debugger` to do that if you have not permission error.

Configure your npm mirror as that [faq](https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md#weex-toolkit-%E5%AE%89%E8%A3%85%E7%BC%93%E6%85%A2), then run the `weex debug` command again, if it does not re-install the `weex-debugger`, maybe you need to delete files on `~/.xtoolkit/node_modules/weex-debugger`.

 Hope it can help you.

**Comment by qld-cf** [comment]
@liuruizhe728 解决了吗  the same to you
