### ISSUE TITLE
weex-debugger升级到最新版，无法使用

### ISSUE THREAD

**Issue by fanlvwen** [weexteam/weex-debugger#34]
![image](https://user-images.githubusercontent.com/36951996/50040791-0ec5b880-0085-11e9-9244-0f351982d269.png)
之前一直使用的weex-devtool,使用命令
`weex xbind debugx weex-devtool
weex debugx src -e index.vue`
调试很正常，
最近weex-debugger升级到最新版，想弃用weex-devtool，按照文档标注：
![image](https://user-images.githubusercontent.com/36951996/50040808-63693380-0085-11e9-8dd6-22a8f4e37680.png)
完全无法运行：
![image](https://user-images.githubusercontent.com/36951996/50040864-5bf65a00-0086-11e9-937e-a3358e985570.png)

请问我想要debug整个文件夹，改怎么办？翻遍无数网站都找不到答案，我的app不是单页面应用，weex debug index.vue没用啊

**Comment by erha19** [comment]
see https://github.com/weexteam/weex-toolkit/issues/517
