### ISSUE TITLE
运行官方源码incubator-weex，debug直接崩溃

### ISSUE THREAD

**Issue by fanlvwen** [weexteam/weex-debugger#35]
1.android studio运行incubator-weex/android,替换本机ip之后，安装到手机上
2.weex create一个新项目，weex preview没问题，关闭preview后开启debug：weex debug,自动打开chrome后出现二维码，
3.打开playground，扫码之后，app直接崩溃
playground配置如下：
![image](https://user-images.githubusercontent.com/36951996/50041279-75e76b00-008d-11e9-843e-ddb754b02b27.png)
我什么都没改，都直接崩溃，还能玩吗？？？？
![image](https://user-images.githubusercontent.com/36951996/50041297-9e6f6500-008d-11e9-9de1-384dc5dfb305.png)
你们这个使用文档真的是认真写的吗？ 这个debug我搞了两天了，各种错误，心好累

**Comment by Hasten50** [comment]
the same with u 
不一样的是..我是iOS的

**Comment by erha19** [comment]
see https://github.com/weexteam/weex-toolkit/issues/517
