### ISSUE TITLE
call [__WEEX_CALL_JAVASCRIPT__] error: jsframework has no such api

### ISSUE THREAD

**Issue by zjutkz** [weexteam/weex-debugger#41]
**信息**
- platform：Android

- os version：9.0

- Weex sdk version：0.20.0.2

- js framework version：0.29.0

- DSL用的vue，weex-vue-framework version：2.5.16-weex.5

- weex debugger version：v1.3.0

**表现**
使用weex debug扫码后，所有的Weex页面都无法加载，原因是App内的Weex页面都有网络请求，在调用完native的module之后需要callback，而callback回js的时候需要调用`__WEEX_CALL_JAVASCRIPT__`这个方法。
我自己debug了半天jsf的源码也没发现是啥问题。。而把weex sdk降级回0.18.0就没问题了(由于weex sdk降级了，所以对应的jsm和weex-vue-framework的版本也对应的降级了)。

**Comment by erha19** [comment]
@zjutkz 对齐一下你们的版本 https://weex.apache.org/zh/guide/debug/integrate-devtool-to-android.html#%E7%89%88%E6%9C%AC%E5%85%BC%E5%AE%B9

**Comment by zjutkz** [comment]
@erha19 It works,Thx.
