### ISSUE TITLE
debug 的时候，chrome控制台一直提示: jsLog: [WDS] Disconnected! 

### ISSUE THREAD

**Issue by swingboy** [weexteam/weex-debugger#44]

**Comment by wavesbig** [comment]
同求,并且console.log只执行一次

**Comment by wavesbig** [comment]
阿里对自己的项目这么不重视吗都没人回

**Comment by erha19** [comment]
@569202812 `weex-debugger`升级到`1.3.4`版本即可解决，1.3.2-1.3.3版本为问题版本。

**Comment by wavesbig** [comment]
> @ 569202812 `weex-debugger`升级到`1.3.4`版本即可解决，1.3.2-1.3.3版本为问题版本。

好的万分感谢
