### ISSUE TITLE
weex debug 扫码二维码进入debug模式后点击  JS Debug（NO）手机一直加载中没有显示扫码页面

### ISSUE THREAD

**Issue by cykl4451** [weexteam/weex-debugger#8]
![image](https://user-images.githubusercontent.com/30775058/36716238-849f07b4-1bd4-11e8-8319-5ac3ea3e7f0a.png)

**Comment by erha19** [comment]
@cykl4451 please show me the log on your terminal console.

**Comment by cykl4451** [comment]
手机就是一直在转圈加载中，没有日志，空白页

**Comment by cykl4451** [comment]
@erha19 这是版本号，手机上没有日志，空白页，一直在转圈加载中状态![image](https://user-images.githubusercontent.com/30775058/36885298-18649308-1e21-11e8-9770-7de7f2b9f9d3.png)

**Comment by erha19** [comment]
@cykl4451 show me the log while you running `weex debug --verbose`.

**Comment by cykl4451** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/30775058/37076031-9a023a68-220f-11e8-9f93-72a822e38583.png)控制台地洞debug，安卓手机扫码进入debug的
![image](https://user-images.githubusercontent.com/30775058/37076083-d78afd84-220f-11e8-9401-04cebdca913c.png)

**Comment by zengxiaoting** [comment]
![weex-debug](https://user-images.githubusercontent.com/8512378/37320766-3380a4a0-26b0-11e8-8b4c-236d0ddc2ebb.png)
我这边遇到了相同的问题，截图是weex debug --verbose的日志@erha19

**Comment by yongningfu** [comment]
根本用不了  palyground二维码扫描没用。。。。。。

**Comment by erha19** [comment]
@yongningfu PC和手机需要在同一个局域网下，且不要有网络代理程序在运行 @zengxiaoting 提供一下你的weex版本，尝试升级一下你的`weex-debugger`,  `weex update weex-debugger`.

**Comment by yongningfu** [comment]
@erha19  很纳闷  npm start 后  发现 只有chrome可以打开预览页面  其他浏览器同一ip地址都打不开，手机在同一个局域网下面也打不开这个页面， 是不是webpack-dev-server配置哪里出现问题?  window平台

**Comment by yongningfu** [comment]
@erha19  在webpackdevserver配置，把host去掉后， 用localhost访问，就任何浏览器都可以打开

**Comment by g770728y** [comment]
我这边的情况，确实是网络代理影响，谢谢
