### ISSUE TITLE
weex deubg 没有打印日子

### ISSUE THREAD

**Issue by cykl4451** [weexteam/weex-debugger#9]
![image](https://user-images.githubusercontent.com/30775058/36768062-2948b500-1c78-11e8-8050-3aa291da829e.png)

**Comment by fanlvwen** [comment]
请问你是直接在安卓代码中开启的debug，类似
WXEnvironment.sDebugServerConnectable = true;
WXEnvironment.sRemoteDebugMode = true;
WXEnvironment.sRemoteDebugProxyUrl = "ws://" + host + ":8088/debugProxy/native";

还是扫码实现的debug

**Comment by erha19** [comment]
@cykl4451 any error code log on your terminal console?

**Comment by cykl4451** [comment]
@erha19 idea启动weex debug  ...浏览器展示，手机扫浏览器上的二维码

**Comment by erha19** [comment]
@cykl4451 chromium maybe install success on your platform, see https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md#weex-%E5%B7%A5%E5%85%B7%E9%93%BE%E7%9B%B8%E5%85%B3%E4%BE%9D%E8%B5%96%E4%B8%8B%E8%BD%BD%E7%BC%93%E6%85%A2 to re-install your `weex-debugger`.
